### ISSUE TITLE
Need sample

### ISSUE THREAD

**Issue by manonaga2188** [TyrinCRM/RichTextEditor#1]
Can you provide sample project ?

**Comment by TimPurdum** [comment]
@manonaga2188 , this project is about a year old for me, and I can't get it to build right now based on my own notes, sorry! I'm working on a lot of other projects, but I'll see if I can get back to this in the near future.

**Comment by TimPurdum** [comment]
@manonaga2188 update has working Android implementation. Not great, but I got it to run.
